# -*- encoding: utf-8 -*-

=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "textmagic_rest_client/version"

Gem::Specification.new do |s|
  s.name        = "textmagic_rest_client"
  s.version     = TextmagicRestClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Textmagic"]
  s.email       = ["support@textmagic.com"]
  s.homepage    = "https://docs.textmagic.com"
  s.summary     = "This library provides you with an easy way of sending SMS and receiving replies by integrating the Textmagic SMS Gateway into your Ruby application."
  s.description = "Textmagic Ruby SDK"
  s.license     = "MIT"
  s.required_ruby_version = "> 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
