=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextmagicRestClient::GetMessagingStatResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TextmagicRestClient::GetMessagingStatResponse do
  let(:instance) { TextmagicRestClient::GetMessagingStatResponse.new }

  describe 'test an instance of GetMessagingStatResponse' do
    it 'should create an instance of GetMessagingStatResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TextmagicRestClient::GetMessagingStatResponse)
    end
  end

end
