=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextmagicRestClient::GetCountriesResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TextmagicRestClient::GetCountriesResponse do
  let(:instance) { TextmagicRestClient::GetCountriesResponse.new }

  describe 'test an instance of GetCountriesResponse' do
    it 'should create an instance of GetCountriesResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TextmagicRestClient::GetCountriesResponse)
    end
  end

end
