=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextmagicRestClient::MuteChatsBulkInputObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TextmagicRestClient::MuteChatsBulkInputObject do
  let(:instance) { TextmagicRestClient::MuteChatsBulkInputObject.new }

  describe 'test an instance of MuteChatsBulkInputObject' do
    it 'should create an instance of MuteChatsBulkInputObject' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TextmagicRestClient::MuteChatsBulkInputObject)
    end
  end

  describe 'test attribute "ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "all"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "_for"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
