=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TextmagicRestClient::UpdateChatDesktopNotificationSettingsInputObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TextmagicRestClient::UpdateChatDesktopNotificationSettingsInputObject do
  let(:instance) { TextmagicRestClient::UpdateChatDesktopNotificationSettingsInputObject.new }

  describe 'test an instance of UpdateChatDesktopNotificationSettingsInputObject' do
    it 'should create an instance of UpdateChatDesktopNotificationSettingsInputObject' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TextmagicRestClient::UpdateChatDesktopNotificationSettingsInputObject)
    end
  end

  describe 'test attribute "play_sound"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "show_notifications"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "show_text"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "sound_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
