=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module TextmagicRestClient
  class Chat
    # Chat ID.
    attr_accessor :id

    attr_accessor :original_id

    # Chat partner's phone number.
    attr_accessor :phone

    attr_accessor :contact

    # If this field has a value, it means that the chat phone number has been unsubscribed from you and this value is an ID of an Unsubscribed contact entity. See [Get all unsubscribed contacts](https://docs.textmagic.com/#operation/getUnsubscribers).
    attr_accessor :unsubscribed_contact_id

    # Total unread incoming messages.
    attr_accessor :unread

    # Time when the last incoming message arrived at this chat.
    attr_accessor :updated_at

    # Chat status:   * **a** - Active;   * **c** - Closed;   * **d** - Deleted. 
    attr_accessor :status

    # Indicates when the chat is muted.
    attr_accessor :mute

    # The last message content of a chat.
    attr_accessor :last_message

    # Last message type: * **ci** - incoming call; * **co** - outgoing call; * **i** - incoming message; * **o** - outgoing message. 
    attr_accessor :direction

    # Used for chats prices.
    attr_accessor :reply_options_type

    # If filled, the value will be used as a sender number for all outgoing messages of a chat.
    attr_accessor :from

    # Date and time until the chat will be muted.
    attr_accessor :muted_until

    # Time left untill the chat will be unmuted (seconds).
    attr_accessor :time_left_mute

    attr_accessor :country

    # Indicates when the chat is pinned.
    attr_accessor :pinned

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'original_id' => :'originalId',
        :'phone' => :'phone',
        :'contact' => :'contact',
        :'unsubscribed_contact_id' => :'unsubscribedContactId',
        :'unread' => :'unread',
        :'updated_at' => :'updatedAt',
        :'status' => :'status',
        :'mute' => :'mute',
        :'last_message' => :'lastMessage',
        :'direction' => :'direction',
        :'reply_options_type' => :'replyOptionsType',
        :'from' => :'from',
        :'muted_until' => :'mutedUntil',
        :'time_left_mute' => :'timeLeftMute',
        :'country' => :'country',
        :'pinned' => :'pinned'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'original_id' => :'Integer',
        :'phone' => :'String',
        :'contact' => :'Contact',
        :'unsubscribed_contact_id' => :'Integer',
        :'unread' => :'Integer',
        :'updated_at' => :'Time',
        :'status' => :'String',
        :'mute' => :'Integer',
        :'last_message' => :'String',
        :'direction' => :'String',
        :'reply_options_type' => :'String',
        :'from' => :'String',
        :'muted_until' => :'Time',
        :'time_left_mute' => :'Integer',
        :'country' => :'Country',
        :'pinned' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'original_id',
        :'contact',
        :'unsubscribed_contact_id',
        :'last_message',
        :'direction',
        :'reply_options_type',
        :'from',
        :'muted_until',
        :'country',
        :'pinned'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TextmagicRestClient::Chat` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TextmagicRestClient::Chat`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'original_id')
        self.original_id = attributes[:'original_id']
      else
        self.original_id = nil
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      else
        self.phone = nil
      end

      if attributes.key?(:'contact')
        self.contact = attributes[:'contact']
      else
        self.contact = nil
      end

      if attributes.key?(:'unsubscribed_contact_id')
        self.unsubscribed_contact_id = attributes[:'unsubscribed_contact_id']
      else
        self.unsubscribed_contact_id = nil
      end

      if attributes.key?(:'unread')
        self.unread = attributes[:'unread']
      else
        self.unread = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'mute')
        self.mute = attributes[:'mute']
      else
        self.mute = nil
      end

      if attributes.key?(:'last_message')
        self.last_message = attributes[:'last_message']
      else
        self.last_message = nil
      end

      if attributes.key?(:'direction')
        self.direction = attributes[:'direction']
      else
        self.direction = nil
      end

      if attributes.key?(:'reply_options_type')
        self.reply_options_type = attributes[:'reply_options_type']
      else
        self.reply_options_type = nil
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'muted_until')
        self.muted_until = attributes[:'muted_until']
      else
        self.muted_until = nil
      end

      if attributes.key?(:'time_left_mute')
        self.time_left_mute = attributes[:'time_left_mute']
      else
        self.time_left_mute = nil
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      else
        self.country = nil
      end

      if attributes.key?(:'pinned')
        self.pinned = attributes[:'pinned']
      else
        self.pinned = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @phone.nil?
        invalid_properties.push('invalid value for "phone", phone cannot be nil.')
      end

      if @unread.nil?
        invalid_properties.push('invalid value for "unread", unread cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @mute.nil?
        invalid_properties.push('invalid value for "mute", mute cannot be nil.')
      end

      if @time_left_mute.nil?
        invalid_properties.push('invalid value for "time_left_mute", time_left_mute cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @phone.nil?
      return false if @unread.nil?
      return false if @updated_at.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["a", "c", "d"])
      return false unless status_validator.valid?(@status)
      return false if @mute.nil?
      direction_validator = EnumAttributeValidator.new('String', ["ci", "co", "i", "o"])
      return false unless direction_validator.valid?(@direction)
      return false if @time_left_mute.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["a", "c", "d"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] direction Object to be assigned
    def direction=(direction)
      validator = EnumAttributeValidator.new('String', ["ci", "co", "i", "o"])
      unless validator.valid?(direction)
        fail ArgumentError, "invalid value for \"direction\", must be one of #{validator.allowable_values}."
      end
      @direction = direction
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          original_id == o.original_id &&
          phone == o.phone &&
          contact == o.contact &&
          unsubscribed_contact_id == o.unsubscribed_contact_id &&
          unread == o.unread &&
          updated_at == o.updated_at &&
          status == o.status &&
          mute == o.mute &&
          last_message == o.last_message &&
          direction == o.direction &&
          reply_options_type == o.reply_options_type &&
          from == o.from &&
          muted_until == o.muted_until &&
          time_left_mute == o.time_left_mute &&
          country == o.country &&
          pinned == o.pinned
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, original_id, phone, contact, unsubscribed_contact_id, unread, updated_at, status, mute, last_message, direction, reply_options_type, from, muted_until, time_left_mute, country, pinned].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TextmagicRestClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
