=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module TextmagicRestClient
  class DoEmailLookupResponse
    # The email address passed to the call.
    attr_accessor :address

    # The email is `valid` or `invalid`.
    attr_accessor :status

    # The delivery status of the email address is`deliverable`, `undeliverable`. or `unknown`.
    attr_accessor :deliverability

    # The reason why the checked email is invalid/undeliverable.
    attr_accessor :reason

    # The risk score of the email is`high`, `medium`, `low` or `null`.
    attr_accessor :risk

    # The email address type (domain) is `free` or `corporate`.
    attr_accessor :address_type

    # This is `true` if the domain is in the list of disposable email addresses; otherwise, it returns as `false`.
    attr_accessor :is_disposable_address

    # Null if nothing is suggested; however, if there is a potential typo in the email address, the closest suggestion is provided.
    attr_accessor :suggestion

    # Checks the mailbox part of the email to see whether it matches a specific role type (‘admin’, ‘sales’, ‘webmaster’).
    attr_accessor :email_role

    # The local part of the email address.
    attr_accessor :local_part

    # The domain part of the email address.
    attr_accessor :domain_part

    # Email exchange server domain name (MX record value).
    attr_accessor :exchange

    # MX record preference.
    attr_accessor :preference

    # `true` if the email address exists in the Textmagic whitelist. 
    attr_accessor :is_in_white_list

    # `true` if the email address exists in the Textmagic blacklist. 
    attr_accessor :is_in_black_list

    # `true` if the email address domain has an MX record. 
    attr_accessor :has_mx

    # `true` if the email address domain has an A record (IPv4). 
    attr_accessor :has_aa

    # `true` if the email address domain has an AAAA record (IPv6). 
    attr_accessor :has_aaaa

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'address' => :'address',
        :'status' => :'status',
        :'deliverability' => :'deliverability',
        :'reason' => :'reason',
        :'risk' => :'risk',
        :'address_type' => :'addressType',
        :'is_disposable_address' => :'isDisposableAddress',
        :'suggestion' => :'suggestion',
        :'email_role' => :'emailRole',
        :'local_part' => :'localPart',
        :'domain_part' => :'domainPart',
        :'exchange' => :'exchange',
        :'preference' => :'preference',
        :'is_in_white_list' => :'isInWhiteList',
        :'is_in_black_list' => :'isInBlackList',
        :'has_mx' => :'hasMx',
        :'has_aa' => :'hasAa',
        :'has_aaaa' => :'hasAaaa'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'address' => :'String',
        :'status' => :'String',
        :'deliverability' => :'String',
        :'reason' => :'String',
        :'risk' => :'String',
        :'address_type' => :'String',
        :'is_disposable_address' => :'Boolean',
        :'suggestion' => :'String',
        :'email_role' => :'String',
        :'local_part' => :'String',
        :'domain_part' => :'String',
        :'exchange' => :'String',
        :'preference' => :'Integer',
        :'is_in_white_list' => :'Boolean',
        :'is_in_black_list' => :'Boolean',
        :'has_mx' => :'Boolean',
        :'has_aa' => :'Boolean',
        :'has_aaaa' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'reason',
        :'suggestion',
        :'email_role',
        :'exchange',
        :'preference',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TextmagicRestClient::DoEmailLookupResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TextmagicRestClient::DoEmailLookupResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      else
        self.address = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'deliverability')
        self.deliverability = attributes[:'deliverability']
      else
        self.deliverability = nil
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      else
        self.reason = nil
      end

      if attributes.key?(:'risk')
        self.risk = attributes[:'risk']
      else
        self.risk = nil
      end

      if attributes.key?(:'address_type')
        self.address_type = attributes[:'address_type']
      else
        self.address_type = nil
      end

      if attributes.key?(:'is_disposable_address')
        self.is_disposable_address = attributes[:'is_disposable_address']
      else
        self.is_disposable_address = nil
      end

      if attributes.key?(:'suggestion')
        self.suggestion = attributes[:'suggestion']
      else
        self.suggestion = nil
      end

      if attributes.key?(:'email_role')
        self.email_role = attributes[:'email_role']
      else
        self.email_role = nil
      end

      if attributes.key?(:'local_part')
        self.local_part = attributes[:'local_part']
      else
        self.local_part = nil
      end

      if attributes.key?(:'domain_part')
        self.domain_part = attributes[:'domain_part']
      else
        self.domain_part = nil
      end

      if attributes.key?(:'exchange')
        self.exchange = attributes[:'exchange']
      else
        self.exchange = nil
      end

      if attributes.key?(:'preference')
        self.preference = attributes[:'preference']
      else
        self.preference = nil
      end

      if attributes.key?(:'is_in_white_list')
        self.is_in_white_list = attributes[:'is_in_white_list']
      else
        self.is_in_white_list = nil
      end

      if attributes.key?(:'is_in_black_list')
        self.is_in_black_list = attributes[:'is_in_black_list']
      else
        self.is_in_black_list = nil
      end

      if attributes.key?(:'has_mx')
        self.has_mx = attributes[:'has_mx']
      else
        self.has_mx = nil
      end

      if attributes.key?(:'has_aa')
        self.has_aa = attributes[:'has_aa']
      else
        self.has_aa = nil
      end

      if attributes.key?(:'has_aaaa')
        self.has_aaaa = attributes[:'has_aaaa']
      else
        self.has_aaaa = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @address.nil?
        invalid_properties.push('invalid value for "address", address cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @deliverability.nil?
        invalid_properties.push('invalid value for "deliverability", deliverability cannot be nil.')
      end

      if @risk.nil?
        invalid_properties.push('invalid value for "risk", risk cannot be nil.')
      end

      if @address_type.nil?
        invalid_properties.push('invalid value for "address_type", address_type cannot be nil.')
      end

      if @is_disposable_address.nil?
        invalid_properties.push('invalid value for "is_disposable_address", is_disposable_address cannot be nil.')
      end

      if @local_part.nil?
        invalid_properties.push('invalid value for "local_part", local_part cannot be nil.')
      end

      if @domain_part.nil?
        invalid_properties.push('invalid value for "domain_part", domain_part cannot be nil.')
      end

      if @is_in_white_list.nil?
        invalid_properties.push('invalid value for "is_in_white_list", is_in_white_list cannot be nil.')
      end

      if @is_in_black_list.nil?
        invalid_properties.push('invalid value for "is_in_black_list", is_in_black_list cannot be nil.')
      end

      if @has_mx.nil?
        invalid_properties.push('invalid value for "has_mx", has_mx cannot be nil.')
      end

      if @has_aa.nil?
        invalid_properties.push('invalid value for "has_aa", has_aa cannot be nil.')
      end

      if @has_aaaa.nil?
        invalid_properties.push('invalid value for "has_aaaa", has_aaaa cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @address.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["valid", "invalid"])
      return false unless status_validator.valid?(@status)
      return false if @deliverability.nil?
      return false if @risk.nil?
      risk_validator = EnumAttributeValidator.new('String', ["high", "medium", "low", "unknown"])
      return false unless risk_validator.valid?(@risk)
      return false if @address_type.nil?
      address_type_validator = EnumAttributeValidator.new('String', ["corporate", "free"])
      return false unless address_type_validator.valid?(@address_type)
      return false if @is_disposable_address.nil?
      return false if @local_part.nil?
      return false if @domain_part.nil?
      return false if @is_in_white_list.nil?
      return false if @is_in_black_list.nil?
      return false if @has_mx.nil?
      return false if @has_aa.nil?
      return false if @has_aaaa.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["valid", "invalid"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] risk Object to be assigned
    def risk=(risk)
      validator = EnumAttributeValidator.new('String', ["high", "medium", "low", "unknown"])
      unless validator.valid?(risk)
        fail ArgumentError, "invalid value for \"risk\", must be one of #{validator.allowable_values}."
      end
      @risk = risk
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] address_type Object to be assigned
    def address_type=(address_type)
      validator = EnumAttributeValidator.new('String', ["corporate", "free"])
      unless validator.valid?(address_type)
        fail ArgumentError, "invalid value for \"address_type\", must be one of #{validator.allowable_values}."
      end
      @address_type = address_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          address == o.address &&
          status == o.status &&
          deliverability == o.deliverability &&
          reason == o.reason &&
          risk == o.risk &&
          address_type == o.address_type &&
          is_disposable_address == o.is_disposable_address &&
          suggestion == o.suggestion &&
          email_role == o.email_role &&
          local_part == o.local_part &&
          domain_part == o.domain_part &&
          exchange == o.exchange &&
          preference == o.preference &&
          is_in_white_list == o.is_in_white_list &&
          is_in_black_list == o.is_in_black_list &&
          has_mx == o.has_mx &&
          has_aa == o.has_aa &&
          has_aaaa == o.has_aaaa
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [address, status, deliverability, reason, risk, address_type, is_disposable_address, suggestion, email_role, local_part, domain_part, exchange, preference, is_in_white_list, is_in_black_list, has_mx, has_aa, has_aaaa].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TextmagicRestClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
