=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module TextmagicRestClient
  class GetContactsAutocompleteResponseItem
    # Id of entity. 0 if object is a reply.
    attr_accessor :entity_id

    # Entry type: * **contact** if it is related to a contact; * **list** if it is related to a contact list; * **reply** if it is related to an incoming message. 
    attr_accessor :entity_type

    # ID of the contact/list if entityType is contact/list OR phone number if entityType is reply.
    attr_accessor :value

    # Name of the contact/list if entityType is contact/list OR phone number if entityType is reply.
    attr_accessor :label

    # If contact or list was shared by another sub-account, the name of this user will be shown.
    attr_accessor :shared_by

    # If contact or list was shared by another sub-account then `true` will be set.
    attr_accessor :is_shared

    # Contact avatar URI.
    attr_accessor :avatar

    # If contact has been marked as favorite.
    attr_accessor :favorited

    # Owner ID of the contact/list (if it was shared).
    attr_accessor :user_id

    attr_accessor :country_name

    attr_accessor :qposition

    attr_accessor :rposition

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'entity_id' => :'entityId',
        :'entity_type' => :'entityType',
        :'value' => :'value',
        :'label' => :'label',
        :'shared_by' => :'sharedBy',
        :'is_shared' => :'isShared',
        :'avatar' => :'avatar',
        :'favorited' => :'favorited',
        :'user_id' => :'userId',
        :'country_name' => :'countryName',
        :'qposition' => :'qposition',
        :'rposition' => :'rposition'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'entity_id' => :'Integer',
        :'entity_type' => :'String',
        :'value' => :'String',
        :'label' => :'String',
        :'shared_by' => :'String',
        :'is_shared' => :'Boolean',
        :'avatar' => :'String',
        :'favorited' => :'Boolean',
        :'user_id' => :'Integer',
        :'country_name' => :'String',
        :'qposition' => :'Integer',
        :'rposition' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'avatar',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TextmagicRestClient::GetContactsAutocompleteResponseItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TextmagicRestClient::GetContactsAutocompleteResponseItem`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'entity_id')
        self.entity_id = attributes[:'entity_id']
      else
        self.entity_id = nil
      end

      if attributes.key?(:'entity_type')
        self.entity_type = attributes[:'entity_type']
      else
        self.entity_type = nil
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      else
        self.value = nil
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      else
        self.label = nil
      end

      if attributes.key?(:'shared_by')
        self.shared_by = attributes[:'shared_by']
      else
        self.shared_by = nil
      end

      if attributes.key?(:'is_shared')
        self.is_shared = attributes[:'is_shared']
      else
        self.is_shared = nil
      end

      if attributes.key?(:'avatar')
        self.avatar = attributes[:'avatar']
      else
        self.avatar = nil
      end

      if attributes.key?(:'favorited')
        self.favorited = attributes[:'favorited']
      else
        self.favorited = nil
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      else
        self.user_id = nil
      end

      if attributes.key?(:'country_name')
        self.country_name = attributes[:'country_name']
      else
        self.country_name = nil
      end

      if attributes.key?(:'qposition')
        self.qposition = attributes[:'qposition']
      else
        self.qposition = nil
      end

      if attributes.key?(:'rposition')
        self.rposition = attributes[:'rposition']
      else
        self.rposition = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @entity_id.nil?
        invalid_properties.push('invalid value for "entity_id", entity_id cannot be nil.')
      end

      if @entity_type.nil?
        invalid_properties.push('invalid value for "entity_type", entity_type cannot be nil.')
      end

      if @value.nil?
        invalid_properties.push('invalid value for "value", value cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @shared_by.nil?
        invalid_properties.push('invalid value for "shared_by", shared_by cannot be nil.')
      end

      if @is_shared.nil?
        invalid_properties.push('invalid value for "is_shared", is_shared cannot be nil.')
      end

      if @favorited.nil?
        invalid_properties.push('invalid value for "favorited", favorited cannot be nil.')
      end

      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @country_name.nil?
        invalid_properties.push('invalid value for "country_name", country_name cannot be nil.')
      end

      if @qposition.nil?
        invalid_properties.push('invalid value for "qposition", qposition cannot be nil.')
      end

      if @rposition.nil?
        invalid_properties.push('invalid value for "rposition", rposition cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @entity_id.nil?
      return false if @entity_type.nil?
      entity_type_validator = EnumAttributeValidator.new('String', ["reply", "contact", "list"])
      return false unless entity_type_validator.valid?(@entity_type)
      return false if @value.nil?
      return false if @label.nil?
      return false if @shared_by.nil?
      return false if @is_shared.nil?
      return false if @favorited.nil?
      return false if @user_id.nil?
      return false if @country_name.nil?
      return false if @qposition.nil?
      return false if @rposition.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] entity_type Object to be assigned
    def entity_type=(entity_type)
      validator = EnumAttributeValidator.new('String', ["reply", "contact", "list"])
      unless validator.valid?(entity_type)
        fail ArgumentError, "invalid value for \"entity_type\", must be one of #{validator.allowable_values}."
      end
      @entity_type = entity_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          entity_id == o.entity_id &&
          entity_type == o.entity_type &&
          value == o.value &&
          label == o.label &&
          shared_by == o.shared_by &&
          is_shared == o.is_shared &&
          avatar == o.avatar &&
          favorited == o.favorited &&
          user_id == o.user_id &&
          country_name == o.country_name &&
          qposition == o.qposition &&
          rposition == o.rposition
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [entity_id, entity_type, value, label, shared_by, is_shared, avatar, favorited, user_id, country_name, qposition, rposition].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TextmagicRestClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
