=begin
#Textmagic API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2

Generated by: https://openapi-generator.tech
Generator version: 7.5.0

=end

require 'date'
require 'time'

module TextmagicRestClient
  class GetAvailableSenderSettingOptionsResponse
    # Array of dedicated number strings.
    attr_accessor :dedicated

    # Array of verified account phone numbers (currently only one).
    attr_accessor :user

    # Array of shared number strings.
    attr_accessor :shared

    # Array of alphanumeric sender IDs.
    attr_accessor :sender_ids

    # Array of alphanumeric sender IDs.
    attr_accessor :user_carrier_twilio

    # Array of alphanumeric sender IDs.
    attr_accessor :user_carrier_vonage

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'dedicated' => :'dedicated',
        :'user' => :'user',
        :'shared' => :'shared',
        :'sender_ids' => :'senderIds',
        :'user_carrier_twilio' => :'userCarrierTwilio',
        :'user_carrier_vonage' => :'userCarrierVonage'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'dedicated' => :'Array<String>',
        :'user' => :'Array<String>',
        :'shared' => :'Array<String>',
        :'sender_ids' => :'Array<String>',
        :'user_carrier_twilio' => :'Array<String>',
        :'user_carrier_vonage' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TextmagicRestClient::GetAvailableSenderSettingOptionsResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TextmagicRestClient::GetAvailableSenderSettingOptionsResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'dedicated')
        if (value = attributes[:'dedicated']).is_a?(Array)
          self.dedicated = value
        end
      else
        self.dedicated = nil
      end

      if attributes.key?(:'user')
        if (value = attributes[:'user']).is_a?(Array)
          self.user = value
        end
      else
        self.user = nil
      end

      if attributes.key?(:'shared')
        if (value = attributes[:'shared']).is_a?(Array)
          self.shared = value
        end
      else
        self.shared = nil
      end

      if attributes.key?(:'sender_ids')
        if (value = attributes[:'sender_ids']).is_a?(Array)
          self.sender_ids = value
        end
      else
        self.sender_ids = nil
      end

      if attributes.key?(:'user_carrier_twilio')
        if (value = attributes[:'user_carrier_twilio']).is_a?(Array)
          self.user_carrier_twilio = value
        end
      else
        self.user_carrier_twilio = nil
      end

      if attributes.key?(:'user_carrier_vonage')
        if (value = attributes[:'user_carrier_vonage']).is_a?(Array)
          self.user_carrier_vonage = value
        end
      else
        self.user_carrier_vonage = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @dedicated.nil?
        invalid_properties.push('invalid value for "dedicated", dedicated cannot be nil.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @shared.nil?
        invalid_properties.push('invalid value for "shared", shared cannot be nil.')
      end

      if @sender_ids.nil?
        invalid_properties.push('invalid value for "sender_ids", sender_ids cannot be nil.')
      end

      if @user_carrier_twilio.nil?
        invalid_properties.push('invalid value for "user_carrier_twilio", user_carrier_twilio cannot be nil.')
      end

      if @user_carrier_vonage.nil?
        invalid_properties.push('invalid value for "user_carrier_vonage", user_carrier_vonage cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @dedicated.nil?
      return false if @user.nil?
      return false if @shared.nil?
      return false if @sender_ids.nil?
      return false if @user_carrier_twilio.nil?
      return false if @user_carrier_vonage.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          dedicated == o.dedicated &&
          user == o.user &&
          shared == o.shared &&
          sender_ids == o.sender_ids &&
          user_carrier_twilio == o.user_carrier_twilio &&
          user_carrier_vonage == o.user_carrier_vonage
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [dedicated, user, shared, sender_ids, user_carrier_twilio, user_carrier_vonage].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TextmagicRestClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
